name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.4, 2.12.10, 2.11.12]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v5
      - name: Run Tests
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck test
